// <auto-generated />
using System;
using DoAnTotNghiep.Models.EntityModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnTotNghiep.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231223031648_AddTypeDiss")]
    partial class AddTypeDiss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Account", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountRole")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Candidate", b =>
                {
                    b.Property<Guid>("CandidateID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrpitons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Comment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiscussID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AccountUserID");

                    b.HasIndex("DiscussID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.CvLibrary", b =>
                {
                    b.Property<Guid>("CvID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CvFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CvID");

                    b.ToTable("CvLibraries");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Discuss", b =>
                {
                    b.Property<Guid>("DiscussID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscussID");

                    b.HasIndex("AccountUserID");

                    b.ToTable("Discusses");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Employer", b =>
                {
                    b.Property<Guid>("EmployerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("Descrpitons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployerID");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Like", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscussID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AccountUserID");

                    b.HasIndex("DiscussID");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Candidate", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Account")
                        .WithOne("Candidate")
                        .HasForeignKey("DoAnTotNghiep.Models.EntityModels.Candidate", "CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Comment", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountUserID");

                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Discuss", "Discuss")
                        .WithMany("Comments")
                        .HasForeignKey("DiscussID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Discuss");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Discuss", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Account")
                        .WithMany("Discuss")
                        .HasForeignKey("AccountUserID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Employer", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Account")
                        .WithOne("Employer")
                        .HasForeignKey("DoAnTotNghiep.Models.EntityModels.Employer", "EmployerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Like", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Account")
                        .WithMany("Likes")
                        .HasForeignKey("AccountUserID");

                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Discuss", "Discuss")
                        .WithMany("Likes")
                        .HasForeignKey("DiscussID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Discuss");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Message", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep.Models.EntityModels.Account", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Account", b =>
                {
                    b.Navigation("Candidate")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Discuss");

                    b.Navigation("Employer")
                        .IsRequired();

                    b.Navigation("Likes");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EntityModels.Discuss", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
