//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoAnTotNghiep.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5Tr - 10Tr.
        /// </summary>
        public static string _5Tr___10Tr {
            get {
                return ResourceManager.GetString("5Tr - 10Tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết thảo luận.
        /// </summary>
        public static string Bài_viết_thảo_luận {
            get {
                return ResourceManager.GetString("Bài viết thảo luận", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo thống kê.
        /// </summary>
        public static string Báo_cáo_thống_kê {
            get {
                return ResourceManager.GetString("Báo cáo thống kê", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Địa Điểm.
        /// </summary>
        public static string Chọn_Địa_Điểm {
            get {
                return ResourceManager.GetString("Chọn Địa Điểm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng Tôi Đem Lại Cơ Hội Thăng Tiến.
        /// </summary>
        public static string Chúng_Tôi_Đem_Lại_Cơ_Hội_Thăng_Tiến {
            get {
                return ResourceManager.GetString("Chúng Tôi Đem Lại Cơ Hội Thăng Tiến", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ hội nghề nghiệp.
        /// </summary>
        public static string Cơ_hội_nghề_nghiệp {
            get {
                return ResourceManager.GetString("Cơ hội nghề nghiệp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đà Nẵng.
        /// </summary>
        public static string Đà_Nẵng {
            get {
                return ResourceManager.GetString("Đà Nẵng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Đăng_ký {
            get {
                return ResourceManager.GetString("Đăng ký", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Đăng_nhập {
            get {
                return ResourceManager.GetString("Đăng nhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Đăng_xuất {
            get {
                return ResourceManager.GetString("Đăng xuất", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string Danh_sách {
            get {
                return ResourceManager.GetString("Danh sách", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách công ty.
        /// </summary>
        public static string Danh_sách_công_ty {
            get {
                return ResourceManager.GetString("Danh sách công ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tuyển dụng.
        /// </summary>
        public static string Danh_sách_tuyển_dụng {
            get {
                return ResourceManager.GetString("Danh sách tuyển dụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ứng viên.
        /// </summary>
        public static string Danh_sách_ứng_viên {
            get {
                return ResourceManager.GetString("Danh sách ứng viên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Địa_chỉ {
            get {
                return ResourceManager.GetString("Địa chỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Điểm Làm Việc.
        /// </summary>
        public static string Địa_Điểm_Làm_Việc {
            get {
                return ResourceManager.GetString("Địa Điểm Làm Việc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn đàn.
        /// </summary>
        public static string Diễn_đàn {
            get {
                return ResourceManager.GetString("Diễn đàn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ Án Tốt Nghiệp 2025.
        /// </summary>
        public static string Đồ_Án_Tốt_Nghiệp_2025 {
            get {
                return ResourceManager.GetString("Đồ Án Tốt Nghiệp 2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh nghiệp cộng tác.
        /// </summary>
        public static string Doanh_nghiệp_cộng_tác {
            get {
                return ResourceManager.GetString("Doanh nghiệp cộng tác", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Đổi_mật_khẩu {
            get {
                return ResourceManager.GetString("Đổi mật khẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Nội.
        /// </summary>
        public static string Hà_Nội {
            get {
                return ResourceManager.GetString("Hà Nội", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khảo sát.
        /// </summary>
        public static string Khảo_sát {
            get {
                return ResourceManager.GetString("Khảo sát", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Liên_hệ {
            get {
                return ResourceManager.GetString("Liên hệ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi tại.
        /// </summary>
        public static string Liên_hệ_với_chúng_tôi_tại {
            get {
                return ResourceManager.GetString("Liên hệ với chúng tôi tại", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương cơ bản.
        /// </summary>
        public static string Lương_cơ_bản {
            get {
                return ResourceManager.GetString("Lương cơ bản", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thắc mắc hoặc vấn đề cần giải quyết xin vui lòng gửi về tại form liên hệ hoặc thông qua email : phamvanquang@gmail.com.
        /// </summary>
        public static string Mọi_thắc_mắc_hoặc_vấn_đề_cần_giải_quyết_xin_vui_lòng_gửi_về_tại_form_liên_hệ_hoặc_thông_qua_email___phamvanquang_gmail_com {
            get {
                return ResourceManager.GetString("Mọi thắc mắc hoặc vấn đề cần giải quyết xin vui lòng gửi về tại form liên hệ hoặc" +
                        " thông qua email : phamvanquang@gmail.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thông tin về điều khoản và chính sách của chúng tôi xin vui lòng tham khảo thông qua Chat bot hoặc:.
        /// </summary>
        public static string Mọi_thông_tin_về_điều_khoản_và_chính_sách_của_chúng_tôi_xin_vui_lòng_tham_khảo_thông_qua_Chat_bot_hoặc_ {
            get {
                return ResourceManager.GetString("Mọi thông tin về điều khoản và chính sách của chúng tôi xin vui lòng tham khảo th" +
                        "ông qua Chat bot hoặc:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng người đang truy cập:.
        /// </summary>
        public static string Số_lượng_người_đang_truy_cập_ {
            get {
                return ResourceManager.GetString("Số lượng người đang truy cập:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại Đây.
        /// </summary>
        public static string Tại_Đây {
            get {
                return ResourceManager.GetString("Tại Đây", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string Tất_cả {
            get {
                return ResourceManager.GetString("Tất cả", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả công việc.
        /// </summary>
        public static string Tất_cả_công_việc {
            get {
                return ResourceManager.GetString("Tất cả công việc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm.
        /// </summary>
        public static string Thời_gian_làm {
            get {
                return ResourceManager.GetString("Thời gian làm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin doanh nghiệp.
        /// </summary>
        public static string Thông_tin_doanh_nghiệp {
            get {
                return ResourceManager.GetString("Thông tin doanh nghiệp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm.
        /// </summary>
        public static string Tìm_Kiếm {
            get {
                return ResourceManager.GetString("Tìm Kiếm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm việc làm.
        /// </summary>
        public static string Tìm_kiếm_việc_làm {
            get {
                return ResourceManager.GetString("Tìm kiếm việc làm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP. HCM.
        /// </summary>
        public static string TP__HCM {
            get {
                return ResourceManager.GetString("TP. HCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Trang_chủ {
            get {
                return ResourceManager.GetString("Trang chủ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang quản trị.
        /// </summary>
        public static string Trang_quản_trị {
            get {
                return ResourceManager.GetString("Trang quản trị", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trao cơ hội kết nối ước mơ.
        /// </summary>
        public static string Trao_cơ_hội_kết_nối_ước_mơ {
            get {
                return ResourceManager.GetString("Trao cơ hội kết nối ước mơ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trên 10Tr.
        /// </summary>
        public static string Trên_10Tr {
            get {
                return ResourceManager.GetString("Trên 10Tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        public static string Tuyển_dụng {
            get {
                return ResourceManager.GetString("Tuyển dụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng viên tiềm năng.
        /// </summary>
        public static string Ứng_viên_tiềm_năng {
            get {
                return ResourceManager.GetString("Ứng viên tiềm năng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí tuyển dụng.
        /// </summary>
        public static string Vị_trí_tuyển_dụng {
            get {
                return ResourceManager.GetString("Vị trí tuyển dụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vô Vàn Cơ Hội Đang Chờ Bạn.
        /// </summary>
        public static string Vô_Vàn_Cơ_Hội_Đang_Chờ_Bạn {
            get {
                return ResourceManager.GetString("Vô Vàn Cơ Hội Đang Chờ Bạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        public static string Xem_tất_cả {
            get {
                return ResourceManager.GetString("Xem tất cả", resourceCulture);
            }
        }
    }
}
