//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoAnTotNghiep.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng Tôi Đem Lại Cơ Hội Thăng Tiến.
        /// </summary>
        public static string Chúng_Tôi_Đem_Lại_Cơ_Hội_Thăng_Tiến {
            get {
                return ResourceManager.GetString("Chúng Tôi Đem Lại Cơ Hội Thăng Tiến", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Đăng_ký {
            get {
                return ResourceManager.GetString("Đăng ký", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Đăng_nhập {
            get {
                return ResourceManager.GetString("Đăng nhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string Danh_sách {
            get {
                return ResourceManager.GetString("Danh sách", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách công ty.
        /// </summary>
        public static string Danh_sách_công_ty {
            get {
                return ResourceManager.GetString("Danh sách công ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ứng viên.
        /// </summary>
        public static string Danh_sách_ứng_viên {
            get {
                return ResourceManager.GetString("Danh sách ứng viên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn đàn.
        /// </summary>
        public static string Diễn_đàn {
            get {
                return ResourceManager.GetString("Diễn đàn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ Án Tốt Nghiệp 2024.
        /// </summary>
        public static string Đồ_Án_Tốt_Nghiệp_2024 {
            get {
                return ResourceManager.GetString("Đồ Án Tốt Nghiệp 2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Liên_hệ {
            get {
                return ResourceManager.GetString("Liên hệ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thắc mắc hoặc vấn đề cần giải quyết xin vui lòng gửi về tại form liên hệ hoặc thông qua email : vietgiang111001@gmail.com.
        /// </summary>
        public static string Mọi_thắc_mắc_hoặc_vấn_đề_cần_giải_quyết_xin_vui_lòng_gửi_về_tại_form_liên_hệ_hoặc_thông_qua_email___vietgiang111001_gmail_com {
            get {
                return ResourceManager.GetString("Mọi thắc mắc hoặc vấn đề cần giải quyết xin vui lòng gửi về tại form liên hệ hoặc" +
                        " thông qua email : vietgiang111001@gmail.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thông tin về điều khoản và chính sách của chúng tôi xin vui lòng tham khảo thông qua Chat bot hoặc:.
        /// </summary>
        public static string Mọi_thông_tin_về_điều_khoản_và_chính_sách_của_chúng_tôi_xin_vui_lòng_tham_khảo_thông_qua_Chat_bot_hoặc_ {
            get {
                return ResourceManager.GetString("Mọi thông tin về điều khoản và chính sách của chúng tôi xin vui lòng tham khảo th" +
                        "ông qua Chat bot hoặc:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng người đang truy cập:.
        /// </summary>
        public static string Số_lượng_người_đang_truy_cập_ {
            get {
                return ResourceManager.GetString("Số lượng người đang truy cập:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại Đây.
        /// </summary>
        public static string Tại_Đây {
            get {
                return ResourceManager.GetString("Tại Đây", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm.
        /// </summary>
        public static string Tìm_Kiếm {
            get {
                return ResourceManager.GetString("Tìm Kiếm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Trang_chủ {
            get {
                return ResourceManager.GetString("Trang chủ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trao cơ hội kết nối ước mơ.
        /// </summary>
        public static string Trao_cơ_hội_kết_nối_ước_mơ {
            get {
                return ResourceManager.GetString("Trao cơ hội kết nối ước mơ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        public static string Tuyển_dụng {
            get {
                return ResourceManager.GetString("Tuyển dụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vô Vàn Cơ Hội Đang Chờ Bạn.
        /// </summary>
        public static string Vô_Vàn_Cơ_Hội_Đang_Chờ_Bạn {
            get {
                return ResourceManager.GetString("Vô Vàn Cơ Hội Đang Chờ Bạn", resourceCulture);
            }
        }
    }
}
